//Lecture Sept 26 2019



//MakeFile


main.o: main.c



program main.o statistics.o    // this checks the program and then if there are any changes to main.o and statistics.o 
	gcc -o program main.o statistics.o     // if there are changes, then it compiles them


























